env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  'react/no-unknown-property': ['error', { 'ignore': ['css'] }]
#   camelcase: on
